@startuml name diagrama de clases

enum tipoTransaccion{
    COMPRA
    VENTA
}

abstract class Persona{
    - usuario: string
    - contraseña: string
    + iniciarSesion(): void
}

interface Registrar{
    + registrar(): void
}

class Inversor extends Persona{
    - saldoVirtual: number
    - portafolio: Portafolio
    - saldoCaucionado: number

    - validarTarjeta(tarjeta: number, fechaVencimiento: Date, cvc: number): void
    + comprarActivos(activo: Activo, cantidad: number): void
    + venderActivos(activo: Activo, cantidad: number): void
    + consultarPortafolio(): Portafolio
    + ingresarFondos(monto: number, tarjeta: number, fechaVencimiento: Date, cvc: number): void
    + colocarCaucion(monto: number, dias: number): void
    + getters()
}

class Administrador extends Persona{
    + crearActivo(nombre: string, precio: number): Activo
    + modificarActivo(activo: Activo): void
    + eliminarActivo(activo: Activo): void
    + listarUsuarios(): Inversor[]
}

class Portafolio{
    - operaciones: Operacion[]
    - posicionActivo: PosicionActivo[]
    - valorPortafolio: number

    + getGananciaPerdida(): number
    + getHistorial(): Operacion[]
    + getters()
}

class PosicionActivo{
    - cantidad: number
    - activo: Activo
}

class Activo{
    - id: number
    - nombre: string
    - precio: number
    - precioInicial: number
    - variacion: number
    - transacciones: Transaccion[]
    + getPrecioActual(): number
    + getVariacionDiaria(): number
    + getters()
}

class Transaccion{
    - id: number
    - tipo: tipoTransaccion
    - cantidad: number
    - precioEjecutado: number
    - fecha: Date
    + getters()
}

class Simulador{
    - activos: Activo[]

    - realizarCompra(activo: Activo):void
    - realizarVenta(activo: Activo):void
    + Simular(): Activo
}

note left of Activo
    getPrecioActual() retorna el precio
    del activo, que sera asignado
    a precioEjecutado al momento
    de realizar una operacion
    (compra o venta)
end note

note right of Simulador 
    Simular(){
        ... logica de decision compra/venta
        llamar a realizarCompra/realizarVenta
    }
    realizarCompra(){
        ... decision de cantidad de compra y 
            operacion de compra
        sleep(2)
        this.Simular()
    }
    relizarVenta(){
        ...
    }
end note

note left of Inversor 
    colocarCaucion(){
        ... logica de rebote si excede a saldo Virtual
        ... modificacion a saldo virtual
        ... incrementacion de saldo caucionado
    }
    ingresarFondos(){
        this.validarTarjeta()
        ... modificar saldoVirtual
    }
end note

Inversor o-- Portafolio 
Portafolio *-- Transaccion
Transaccion .l.> tipoTransaccion
Administrador ..> Activo
Portafolio o-- PosicionActivo
PosicionActivo --> Activo
Administrador ..> Inversor
Registrar .u.> Inversor
Simulador *-l- Activo

@enduml