@startuml diagrama_de_clases

enum TipoTransaccion {
    COMPRA
    VENTA
}

enum Rol {
    USUARIO
    ADMIN
}

class Inversor {
    - id: number
    - nombre: string
    - email: string
    - contraseña: string
    - saldoVirtual: number
    - rol: Rol
}

class Portafolio {
    - id: number
    - valorPortafolio: number
}

class TenenciaActivo {
    - cantidad: number
    - precioCompra: number
}

class Transaccion {
    - ticker: string
    - tipo: TipoTransaccion
    - cantidad: number
    - precioEjecutado: number
    - fecha: Date
}

class Activo {
    - nombre: string
    - ticker: string
    - precioActual: number
}

' Capa de Servicios (Representación de la lógica)
class InversorService {
    + create()
    + findOne(id)
    + findPerfil(id)
    + cambiarContraseña()
    + findPortafolio()
    + validarTarjeta(): void
    + ingresarFondosTarjeta(): void
    + ingresarFondosTransaccion(): void
}

class SistemaService {
    + procesarCompra(dto, inversorId): void
    + procesarVenta(dto, inversorId): void
}

class AdminService {
    + crearActivo(nombre, precio): Activo
    + modificarActivo(id, dto)
    + listarUsuarios(): Inversor[]
}

class ActivoService {
    + create()
    + findAll()
    + findOne()
    + findAllPaginado()
    + update(id, dto)
    + actualizarActivo(activo, cantidad, tipo)
}

class TransaccionService {
    + findAll()
    + findHistorial()
    + create()
}

' Relaciones
Inversor  *-d-  Portafolio
Portafolio  *-d-  Transaccion
Portafolio *-d- TenenciaActivo
TenenciaActivo -d-> Activo
Transaccion --> Activo
InversorService .l.> Inversor
AdminService .r.> Inversor
ActivoService .r.> Activo
TransaccionService .r.> Transaccion
SistemaService .l.> Activo
AdminService .d.> ActivoService

@enduml