@startuml name diagrama de clases

enum tipoTransaccion{
    COMPRA
    VENTA
}

class Inversor{
    - nombre: string
    - email: string
    - contraseña: string
    - saldoVirtual: number
    - portafolio: Portafolio

    - validarTarjeta(tarjeta: number, fechaVencimiento: Date, cvc: number): void
    + consultarPortafolio(): Portafolio
    + ingresarFondosTarjeta()
    + ingresarFondosTransferencia()
    + retirarFondos()
}

class Admin extends Inversor{
    + crearActivo(nombre: string, precio: number): Activo
    + listarUsuarios(): Inversor[]
}

class Portafolio{
    - transacciones: Transaccion[]
    - tenenciaActivo: TenenciaActivo[]
    - valorPortafolio: number
}

class TenenciaActivo{
    - cantidad: number
    - activo: Activo
    - precioCompra: number
}

class Transaccion{
    - ticker: string
    - tipo: tipoTransaccion
    - cantidad: number
    - precioEjecutado: number
    - fecha: Date
}

class Activo{
    - nombre: string
    - ticker: string
    - precioInicial: number
    - precioActual: number
    - valorMaximo: number
    - valorMinimo: number
    - cantOperaciones: number
    - totalEjecutado: number
    - transacciones: Transaccion[]
}

class Simulador{
    + simularMercado()
}

class Sistema{
    + procesarCompra(dto: CompraActivoDto, inversorId: number)
    + procesarVenta(dto: CompraActivoDto, inversorId: number)
}


note right of Simulador 
    simularMercado(){
        ... decision del activo a operar
        ... decision de compra/venta
        ... decision de la cantidad
        ... creacion de la transaccion 
    }
end note

note left of Inversor 
    ingresarFondos(){
        this.validarTarjeta()
        ... modificar saldoVirtual
    }
end note

Inversor o-- Portafolio 
Portafolio *-- Transaccion
Transaccion .r.> tipoTransaccion
Admin ..> Activo
Portafolio o-- TenenciaActivo
TenenciaActivo --> Activo
Simulador *-l- Activo
Sistema *-d- Activo

@enduml